-- 1.- Mostrar los nombres de los empleados ordenados alfabéticamente (Z...A) 
SELECT NOMBRES, APELLIDO
FROM EMPLEADOS
ORDER BY APELLIDO DESC, NOMBRES DESC;


-- 2.- Seleccionar el nombre, el puesto y la localidad donde trabajan los 
--     empleados con puesto de ‘Soporte’.
SELECT EMPLEADOS.NOMBRES, EMPLEADOS.APELLIDO, PUESTOS.PUESTO, LOCALIDADES.LOCALIDADES
FROM EMPLEADOS
JOIN PUESTOS ON EMPLEADOS.PUESTO_ID = PUESTOS.ID
JOIN DEPARTAMENTOS ON EMPLEADOS.DEPARTAMENTO_ID = DEPARTAMENTOS.ID
JOIN LOCALIDADES ON DEPARTAMENTOS.LOCALIDAD_ID = LOCALIDADES.ID
WHERE PUESTOS.PUESTO = 'Soporte';


-- 3.- Listar los nombres de los empleados cuyo nombre termine con la letra ‘o’.
SELECT NOMBRES, APELLIDO
FROM EMPLEADOS
WHERE NOMBRES LIKE '%o';


-- 4.- Seleccionar el nombre, el puesto y sueldo 
--     de los empleados que trabajan en la localidad Carlos Paz.
SELECT EMPLEADOS.NOMBRES, EMPLEADOS.APELLIDO, PUESTOS.PUESTO, EMPLEADOS.SUELDO
FROM EMPLEADOS
JOIN PUESTOS ON EMPLEADOS.PUESTO_ID = PUESTOS.ID
JOIN DEPARTAMENTOS ON EMPLEADOS.DEPARTAMENTO_ID = DEPARTAMENTOS.ID
JOIN LOCALIDADES ON DEPARTAMENTOS.LOCALIDAD_ID = LOCALIDADES.ID
WHERE LOCALIDADES.LOCALIDAD = 'Carlos Paz';


-- 5.- Seleccionar el nombre, sueldo y localidad donde trabajan
--     de los empleados que tengan un sueldo entre 10000 y 13000.
SELECT EMPLEADOS.NOMBRES, EMPLEADOS.APELLIDO, EMPLEADOS.SUELDO, LOCALIDADES.LOCALIDAD
FROM EMPLEADOS
JOIN DEPARTAMENTOS ON EMPLEADOS.DEPARTAMENTO_ID = DEPARTAMENTOS.ID
JOIN LOCALIDADES ON DEPARTAMENTOS.LOCALIDAD_ID = LOCALIDADES.ID
WHERE EMPLEADOS.SUELDO BETWEEN 10000 AND 13000;


-- 6.- Visualizar los departamentos con más de 5 empleados
SELECT DEPARTAMENTOS.DENOMINACION, COUNT(EMPLEADOS.ID) AS Total_Empleados
FROM DEPARTAMENTOS
JOIN EMPLEADOS ON DEPARTAMENTOS.ID = EMPLEADOS.DEPARTAMENTO_ID
GROUP BY DEPARTAMENTOS.DENOMINACION
HAVING COUNT(EMPLEADOS.ID) > 5;


-- 7.- Nombre de los empleados que trabajan en Córdoba
--     y cuyo puesto sea ‘Analista’ o ‘Programador’.
SELECT EMPLEADOS.NOMBRES, EMPLEADOS.APELLIDO
FROM EMPLEADOS
JOIN PUESTOS ON EMPLEADOS.PUESTO_ID = PUESTOS.ID
JOIN DEPARTAMENTOS ON EMPLEADOS.DEPARTAMENTO_ID = DEPARTAMENTOS.ID
JOIN LOCALIDADES ON DEPARTAMENTOS.LOCALIDAD_ID = LOCALIDADES.ID
WHERE LOCALIDADES.LOCALIDAD = 'Córdoba' 
AND PUESTOS.PUESTO IN ('Analista', 'Programador');

-- 8.- Calcula el sueldo medio de todos los empleados.
SELECT AVG(SUELDO) AS SUELDO_PROMEDIO
FROM EMPLEADOS;


-- 9.- ¿Cuál es el máximo sueldo de los empleados del departamento 10?
SELECT MAX(SUELDO) AS SUELDO_MAXIMO
FROM EMPLEADOS
WHERE DEPARTAMENTO_ID = 10;


-- 10.- Calcula el sueldo mínimo de los empleados del departamento ‘Soporte’.
SELECT MIN(SUELDO) AS SUELDO_MINIMO
FROM EMPLEADOS
JOIN DEPARTAMENTOS ON EMPLEADOS.DEPARTAMENTO_ID = DEPARTAMENTOS.ID
WHERE DEPARTAMENTOS.DENOMINACION = 'Soporte'


-- 11.- Para cada puesto obtener la suma de sueldos.
SELECT PUESTOS.PUESTO, SUM(EMPLEADOS.SUELDO) AS SUMA_SUELDOS
FROM EMPLEADOS
JOIN SUELDOS ON EMPLEADOS.PUESTO_ID = PUESTOS.ID
GROUP BY PUESTOS.PUESTO; 